---
name: build

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push contrib image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            VERSION=${{ vars.VERSION }}
          platforms: linux/amd64,linux/arm64
          target: otel-collector-contrib
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/otel-collector:${{ vars.VERSION }}

      - name: Build and push debug image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          target: otel-collector-contrib-debug
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/otel-collector:${{ vars.VERSION }}-debug
